version: '3.7'
services:
  maddpg:
  # MADDPG Environment (build an appropriate image in ../../images/environment/)
    image: mdde/env:maddpg-ray-latest
    container_name: mdde_maddpg
    depends_on:
      - registry
    networks:
      back:
        aliases:
          - maddpg
    volumes:
      - mdde_shared:/mdde/shared
    environment:
      - REG_PORT=8942
