version: '3.7'
services:
  # Use an override docker-compose that adds the environment configuration
  registry:
  # Registry
    build: 
      context: ../../images/registry
      dockerfile: registry-redis.Dockerfile
    image: mdde/registry:redis-latest
    depends_on:
      - registry_store
#    healthcheck:
#      test: ["CMD", "netstat", "-an", "|", "grep 8942 > /dev/null;", "if [ 0 != $$? ];", "then exit 1;", "fi;"]
#      start_period: 15s
#      interval: 30s
#      retries: 5
    networks:
      back:
        aliases:
          - registry
    volumes:
      - mdde_reg_logs:/mdde/registry-logs
      - mdde_shared:/mdde/shared
  registry_store:
  # Registry storage DB
    image: "redis:5"
    networks:
      back:
        aliases:
          - regstore
  redis_node_0:
  # Data storage node 0
    image: "redis:5"
    networks:
      back:
        aliases:
          - dtnode0
  redis_node_1:
  # Data storage node 1
    image: "redis:5"
    networks:
      back:
        aliases:
          - dtnode1
  redis_node_2:
  # Data storage node 2
    image: "redis:5"
    networks:
      back:
        aliases:
          - dtnode2
  redis_node_3:
  # Data storage node 3
    image: "redis:5"
    networks:
      back:
        aliases:
          - dtnode3
networks:
  back:
  # Network wiring up the MDDE containers
    internal: false
    driver: bridge  
volumes:
  mdde_reg_logs: # MDDE registry logs

  mdde_shared: # MDDE shared volume
