version: '3.7'
services:
  dqn_sa:
  # DQN Environment (build an appropriate image in ../../images/environment/)
    image: mdde/env/ray-dqn-single:latest
    depends_on:
      - registry
    networks:
      back:
        aliases:
          - dqn_sa
    volumes:
      - mdde_shared:/mdde/shared
      - mdde_results:/mdde/results
    environment:
      - REG_HOST=registry
      - REG_PORT=8942
#      - LAUNCH_ARGS=--num_episodes 10
    env_file:
      - ./args.env
volumes:
  mdde_results: # DQN results

